[package]
name = "gs-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.104"
bytemuck = { version = "1.25.2", features = ["derive"] }
naga = "30.0.1"
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.21"
toml = "1.1.6"
wgpu = "30.0.1"

[dev-dependencies]
pollster = "1.0.1"
